import { create } from "zustand";
import { persist } from "zustand/middleware";

// Matches TRIPOLY_HANDOFF.md section 6, minus the ChatStep/currentStep/setStep fixed
// step machine that used to live here. Pure-conversational rebuild (confirmed with
// you): the chat flow no longer has a fixed 1-6 step sequence gating what can be
// answered next — "what's still needed" is now computed live from which of the 7
// fields below are actually present, via lib/fields.ts's nextMissingField(). Removed
// entirely rather than left unused, since nothing after this rebuild reads a step
// number — see components/screens/ChatScreen.tsx, components/ui/ProgressBar.tsx, and
// components/screens/ProcessingScreen.tsx, all updated in the same change.

export type GroupType = "Family" | "Couple" | "Friends" | "Solo";
export type TravelTheme = "Relaxed" | "Adventure" | "Romantic" | "Family" | "Foodie";
export type Language = "EN" | "HI";
export type ItineraryView = "05A" | "05B";

export interface Message {
  id: string;
  role: "bot" | "user" | "error" | "offtopic";
  content: string;
  timestamp: Date;
}

// A photo credit for a dynamically-fetched Unsplash image (lib/unsplash.ts), as opposed
// to the hardcoded ones in lib/constants.ts for the fixed Home-screen destination set.
// `url` is a base64 data URI, not a live Unsplash hotlink — see lib/unsplash.ts for why
// (images.unsplash.com doesn't reliably send CORS headers, which taints the html2canvas
// capture used for PDF export; embedding avoids that for both the PDF and on-screen use).
// Optional everywhere it's used: a failed/missing photo lookup must never block itinerary
// generation, so these fields are absent rather than the itinerary failing outright — every
// call site already has a gradient-placeholder fallback for the no-photo case.
export interface PhotoCredit {
  url: string;
  photographerName: string;
  photographerProfileUrl: string;
}

export interface DayPlan {
  day: number;
  title: string;
  location: string;
  hotel: {
    name: string;
    stars: number;
    description: string;
  };
  meals: {
    breakfast: string;
    lunch: string;
    dinner: string;
  };
  activities: {
    morning: string;
    afternoon: string;
    evening: string;
  };
  estimated_daily_cost: number;
  drive_time: string;
  day_description: string;
  tip: string;
  photo?: PhotoCredit;
  // Approximate coordinates for this day's `location`, city/neighborhood-level accuracy —
  // generated by Claude alongside the rest of the itinerary (lib/claude.ts), sanitized
  // there (range-checked, malformed values dropped) before this ever reaches the client.
  // Optional for the same reason `photo` is: a missing/invalid value must never block
  // itinerary generation. Powers ItineraryMap's per-day pins — a day without these is
  // simply skipped from the map rather than shown incorrectly.
  lat?: number;
  lng?: number;
}

export interface Itinerary {
  trip_summary: {
    name: string;
    destination: string;
    duration_nights: number;
    total_budget: number;
    per_person_budget: number;
    traveler_count: number;
    group_type: string;
    theme: string;
    dates_suggested: string;
    photo?: PhotoCredit;
    // Overall destination coordinates — same sourcing/sanitizing/optionality as DayPlan's
    // lat/lng above. Used as ItineraryMap's fallback single overview pin for trips that
    // have this but no per-day coordinates (notably every trip saved before this feature
    // existed — see useTripStore's persisted savedTrips).
    lat?: number;
    lng?: number;
  };
  days: DayPlan[];
}

// One entry in the "Trips" tab. Every itinerary the user ever generates gets saved here —
// distinct from `itinerary` below, which is just "whichever trip is currently being
// viewed/edited." Persisted to localStorage (see the `persist` wrapper at the bottom of
// this file) so it survives a reload — this app has no backend/login, so "device-local
// only" is the deliberate, agreed scope (confirmed with you): no Supabase, no auth.
export interface SavedTrip {
  id: string;
  savedAt: string; // ISO timestamp — set on first save, bumped on every amendment
  itinerary: Itinerary;
}

function newId() {
  return typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : `${Date.now()}-${Math.random()}`;
}

// Bounds unbounded localStorage growth over months of real use. Well above what any
// single user is likely to accumulate; just a safety net, not an expected ceiling.
const MAX_SAVED_TRIPS = 30;

export interface TripStore {
  // Collected inputs
  name: string;
  destination: string;
  duration: number; // in nights, max 10
  travelDate: string; // free text — an exact date or a flexible month/window, in the user's own words
  totalBudget: number; // in INR
  perPersonBudget: number; // auto-calculated
  travelerCount: number;
  groupType: GroupType | null;
  travelTheme: TravelTheme | null;
  language: Language;

  // Chat state
  messages: Message[];
  isListening: boolean;
  isProcessing: boolean;
  isExtracting: boolean; // true while a chat turn is being resolved via /api/chat-turn

  // Generated itinerary — "the trip currently being viewed/edited" (ItineraryScreen,
  // PdfScreen, Home's continue-trip prompt). Persisted, so it survives a reload.
  itinerary: Itinerary | null;
  itineraryView: ItineraryView; // default: '05A'
  // Which savedTrips entry (if any) `itinerary` corresponds to — lets an amendment
  // update that same entry in place instead of forking a duplicate. Null right after
  // resetTrip(), or if the current itinerary somehow isn't tracked yet.
  activeTripId: string | null;

  // Every itinerary ever generated, newest last. Persisted. Deliberately NOT reset by
  // resetTrip() — starting a new chat flow to plan another trip must never wipe history.
  savedTrips: SavedTrip[];

  // Actions
  setField: <K extends keyof TripStore>(key: K, value: TripStore[K]) => void;
  // Merges several fields in one atomic update — used by the unified chat-turn flow,
  // which can extract multiple fields (e.g. totalBudget AND travelerCount) from a
  // single message. A sequence of individual setField calls would work too, but
  // perPersonBudget needs to be recomputed from whichever of totalBudget/travelerCount
  // is now current after the WHOLE batch lands, not re-derived mid-batch from a stale
  // partial state — this does that recomputation once, atomically, regardless of which
  // of the two fields arrived this turn (or whether both did).
  applyFields: (fields: Partial<TripStore>) => void;
  addMessage: (message: Message) => void;
  // opts.isAmendment: true when this is ItineraryScreen's amend flow updating the trip
  // already being viewed (updates that same savedTrips entry in place). Omitted/false —
  // ProcessingScreen's fresh "generate" — appends a brand-new savedTrips entry instead.
  setItinerary: (itinerary: Itinerary | null, opts?: { isAmendment?: boolean }) => void;
  // Trips tab: reopen a previously-saved trip as the active one.
  loadSavedTrip: (id: string) => void;
  resetTrip: () => void;
}

const initialState = {
  name: "",
  destination: "",
  duration: 0,
  travelDate: "",
  totalBudget: 0,
  perPersonBudget: 0,
  travelerCount: 0,
  groupType: null,
  travelTheme: null,
  language: "EN" as Language,

  messages: [],
  isListening: false,
  isProcessing: false,
  isExtracting: false,

  itinerary: null,
  itineraryView: "05A" as ItineraryView,
  activeTripId: null as string | null,
};

// Only these three survive a reload — everything else in initialState is transient,
// in-progress chat-flow state that shouldn't resume stale after closing the tab.
type PersistedTripState = Pick<TripStore, "itinerary" | "activeTripId" | "savedTrips">;

export const useTripStore = create<TripStore>()(
  persist(
    (set) => ({
      ...initialState,
      savedTrips: [], // outside initialState on purpose — resetTrip() must not clear this

      setField: (key, value) => set({ [key]: value } as Pick<TripStore, typeof key>),
      applyFields: (fields) =>
        set((state) => {
          const totalBudget = fields.totalBudget ?? state.totalBudget;
          const travelerCount = fields.travelerCount ?? state.travelerCount;
          const perPersonBudget =
            totalBudget > 0 && travelerCount > 0 ? Math.round(totalBudget / travelerCount) : state.perPersonBudget;
          return { ...fields, perPersonBudget };
        }),
      addMessage: (message) => set((state) => ({ messages: [...state.messages, message] })),

      setItinerary: (itinerary, opts) =>
        set((state) => {
          if (itinerary === null) {
            return { itinerary: null, activeTripId: null };
          }

          if (opts?.isAmendment && state.activeTripId) {
            const savedAt = new Date().toISOString();
            return {
              itinerary,
              savedTrips: state.savedTrips.map((trip) =>
                trip.id === state.activeTripId ? { ...trip, itinerary, savedAt } : trip,
              ),
            };
          }

          // Fresh generation (or an amendment with no tracked active trip, which
          // shouldn't happen in practice but is handled the same safe way either way).
          const id = newId();
          const entry: SavedTrip = { id, savedAt: new Date().toISOString(), itinerary };
          return {
            itinerary,
            activeTripId: id,
            savedTrips: [...state.savedTrips, entry].slice(-MAX_SAVED_TRIPS),
          };
        }),

      loadSavedTrip: (id) =>
        set((state) => {
          const trip = state.savedTrips.find((t) => t.id === id);
          return trip ? { itinerary: trip.itinerary, activeTripId: trip.id } : {};
        }),

      resetTrip: () => set({ ...initialState }),
    }),
    {
      name: "tripoly-trips",
      // Strips each saved trip's per-day photos before writing to localStorage (keeps
      // trip_summary.photo, the one the Trips-tab card actually displays). Each day photo
      // is a base64-embedded JPEG (lib/unsplash.ts) — up to 10 of them per itinerary — and
      // localStorage's ~5-10MB-per-origin quota would fill up after only a handful of
      // saved trips otherwise. The live in-memory `itinerary` for the trip currently being
      // viewed is untouched by this (partialize only affects what's written to storage),
      // so PdfScreen/ItineraryScreen still show full day photos in the same session that
      // generated them. A trip reopened from the Trips tab after a reload falls back to
      // the same gradient placeholder every other missing-photo case already uses.
      partialize: (state): PersistedTripState => ({
        itinerary: state.itinerary,
        activeTripId: state.activeTripId,
        savedTrips: state.savedTrips.map((trip) => ({
          ...trip,
          itinerary: {
            ...trip.itinerary,
            // eslint-disable-next-line @typescript-eslint/no-unused-vars -- destructuring to drop `photo`, not to use it
            days: trip.itinerary.days.map(({ photo, ...day }) => day),
          },
        })),
      }),
    },
  ),
);
